# Generated by Django 5.2.9 on 2025-12-02 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('plan_contratado', models.CharField(blank=True, max_length=100)),
                ('estado_servicio', models.CharField(default='activo', max_length=50)),
                ('fecha_inicio_contrato', models.DateField(blank=True, null=True)),
                ('fecha_proximo_pago', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('es_perecedero', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigop', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.empresa')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='api.tipoproducto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.producto')),
            ],
        ),
    ]
