# Generated by Django 5.2.9 on 2025-12-09 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
